BEGIN;

DROP TABLE IF EXISTS "animal", "association", "espece", "famille", "tag", "utilisateur", "animal_tag", "demande";
DROP TYPE IF EXISTS sexe, statut, statut_demande;

CREATE TYPE sexe AS ENUM ('Mâle', 'Femelle', 'Inconnu');

CREATE TYPE statut AS ENUM ('En refuge', 'Accueilli', 'Adopté');

CREATE TYPE statut_demande AS ENUM ('En attente', 'Validée', 'Refusée');

CREATE TABLE "utilisateur" (
  "id" int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "email"            TEXT NOT NULL,
  "mot_de_passe"     TEXT NOT NULL
);

CREATE TABLE "association" (
  "id" int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "nom"              TEXT NOT NULL,
  "responsable"      TEXT,
  "rue"              TEXT,
  "commune"          TEXT,
  "code_postal"      TEXT,
  "pays"             TEXT,
  "siret"            TEXT,
  "telephone"        TEXT,
  "utilisateur_id"   INT UNIQUE NOT NULL REFERENCES "utilisateur"("id")
);

CREATE TABLE "famille" (
  "id" int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "nom"              TEXT NOT NULL,
  "telephone"        TEXT,
  "rue"              TEXT,
  "commune"          TEXT,
  "code_postal"      TEXT,
  "pays"             TEXT,
  "hebergement"      TEXT,
  "utilisateur_id"   int UNIQUE NOT NULL REFERENCES "utilisateur"("id")
);

CREATE TABLE "espece" (
  "id" int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "nom"         TEXT NOT NULL,
  "race"        TEXT
);

CREATE TABLE "animal" (
  "id" int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "nom"              TEXT NOT NULL,
  "couleur"          TEXT,
  "age"              INT,
  "photo"            TEXT,
  "sexe"             sexe,
  "description"      TEXT,
  "statut"           statut,
  "association_id"   INT NOT NULL REFERENCES "association"("id"),
  "famille_id"       INT REFERENCES "famille"("id"),
  "espece_id"        INT NOT NULL REFERENCES "espece"("id")
);

CREATE TABLE "tag" (
  "id" int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "nom"         TEXT,
  "description" TEXT
);

CREATE TABLE "animal_tag" (
  "id" int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "animal_id" INT NOT NULL REFERENCES "animal"("id"),
  "tag_id"    INT NOT NULL REFERENCES "tag"("id")
);

CREATE TABLE "demande" (
  "id" int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "famille_id"      INT NOT NULL REFERENCES "famille"("id"),
  "animal_id"       INT NOT NULL REFERENCES "animal"("id"),
  "statut_demande"  statut_demande
);

COMMIT;